jbosstm/lra

- pom.xml
https://github.com/jbosstm/jboss-as/pull/92
Update resteasy to 6.2.10.Final and shrinkwrap to 3.3.2
> Update resteasy to 6.2.10.Final and shrinkwrap to 3.3.2

- pom.xml
- scripts/hudson/narayana.sh
https://issues.redhat.com/browse/JBTM-3926
add missing doxia version and remove community profile (not existing anymore)
> JBTM-3926 leftover

- pom.xml
Update undertow version to 2.3.18.Final
https://github.com/jbosstm/jboss-as/pull/92
> Update undertow version to 2.3.18.Final

- pom.xml
- test/basic/pom.xml
> BUILD SCRIPT ONLY: POMs sorted

- test/crash/pom.xml
Thanks for submitting your Pull Request!
Please refer to our [guidelines for making contributions](https://github.com/jbosstm/narayana/blob/main/CONTRIBUTING.md) when creating your pull request. In particular, it helps the reviewer if you ensure that the:
> POM sorted

- code-coverage/pom.xml
Thanks for submitting your Pull Request!
Please refer to our [guidelines for making contributions](https://github.com/jbosstm/narayana/blob/main/CONTRIBUTING.md) when creating your pull request. In particular, it helps the reviewer if you ensure that the:
!LRA
> Code coverage reporting

- coordinator/pom.xml
- service-base/src/test/java/io/narayana/lra/LRAConstantsTest.java
- test/basic/pom.xml
- test/basic/src/test/java/io/narayana/lra/arquillian/OpenAPIIT.java
- test/crash/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
- test/crash/src/test/java/io/narayana/lra/arquillian/LRACoordinatorRecoveryIT.java
- test/crash/src/test/java/io/narayana/lra/arquillian/UnmanagedTestBase.java
- test/pom.xml
Depends on https://github.com/jbosstm/jboss-as/pull/93
!JDK21 !JACOCO
> Changed path expectations for LRA coordinator

- pom.xml
> BUILD SCRIPT ONLY: Pom sorted

- coordinator/pom.xml
- service-base/src/test/java/io/narayana/lra/LRAConstantsTest.java
- test/basic/src/test/java/io/narayana/lra/arquillian/OpenAPIIT.java
- test/pom.xml
Revert https://issues.redhat.com/browse/JBTM-3954
https://github.com/jbosstm/jboss-as/pull/94
!JACOCO
> Revert https://issues.redhat.com/browse/JBTM-3954

- coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- coordinator/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
- coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
https://issues.redhat.com/browse/JBTM-3964
!JACOCO
I'd like to be able to call periodic recovery on the LRARecoveryModule from the WildFly microprofile-lra subsystem to help with fixing issue [WFLY-20026](https://issues.redhat.com/browse/WFLY-20026).
> JBTM-3964 test for parallel recovery scans

- coordinator/pom.xml
- coordinator/src/main/java/io/narayana/lra/coordinator/management/BrowserCommand.java
https://issues.redhat.com/browse/JBTM-3955
!JDK21 !JACOCO
This PR follows up on https://github.com/jbosstm/lra/pull/14 and adds support for browsing ActiveMQ Journal based logs.
The docs for the feature are to be covered by issue https://issues.redhat.com/browse/JBTM-3784
> JBTM-3955 Support for viewing logs in an activemq journal based store

- test/crash/pom.xml
> BUILD SCRIPT ONLY: Allow for easier IDE handling

- coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
- service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
https://issues.redhat.com/browse/JBTM-3983
Fix error https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/lra/PROFILE=JACOCO,jdk=openJDK21,label=jnlp-agent/29/console
Using Math multiplyExact for test (https://github.com/jbosstm/lra/blob/main/coordinator/src/test/java/io/narayana/lra/coordinator/tools/osb/mbean/ObjStoreBrowserLRATest.java#L100) using Long.MAX_VALUE
> [JBTM-3983] Avoid overflow with timelimit

- client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java
- coordinator/src/main/java/io/narayana/lra/coordinator/management/BrowserCommand.java
- coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
- coordinator/src/test/java/io/narayana/lra/coordinator/tools/osb/mbean/ObjStoreBrowserLRATest.java
- pom.xml
I believe the check style plugin can help us keeping the code cleaner and improve the imports. See the defined rules here:  https://github.com/jbosstm/narayana-checkstyle-config/tree/main
> Enable checkstyle by default

- .github/workflows/jacoco-profile.yml
- .github/workflows/lra-profile.yml
Include github action testing while resolving issues related to default CI
> Add github actions for core and jacoco profile

- pom.xml
> Remove duplicate dependency

- jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
- service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
- test/arquillian-extension/src/main/java/io/narayana/lra/arquillian/appender/MpLraTckAuxiliaryArchiveAppender.java
- test/basic/src/test/java/io/narayana/lra/arquillian/FailingParticipantCallsIT.java
- test/basic/src/test/java/io/narayana/lra/arquillian/LRAParticipantAfterLRAIT.java
- test/basic/src/test/java/io/narayana/lra/arquillian/api/CoordinatorApiIT.java
- test/basic/src/test/java/io/narayana/lra/arquillian/api/NoopParticipant.java
- test/basic/src/test/java/io/narayana/lra/arquillian/resource/LRAParticipant.java
- test/crash/src/test/java/io/narayana/lra/arquillian/LRACoordinatorRecoveryIT.java
https://issues.redhat.com/browse/JBTM-3991
> JBTM-3991 Clean up unnecessary warnings in the test runs

- client/pom.xml
- client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java
- coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/InvalidLBTest.java
- coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LBAlgorithms.java
- coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LBTest.java
- coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LBTestRule.java
- coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
- coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATestBase.java
- service-base/src/main/java/io/narayana/lra/LRAConstants.java
- service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
https://issues.redhat.com/browse/JBTM-3987
This update follows up on #50 by making the load balancing algorithm configurable.
!JACOCO !JDK17 LRA
> Jbtm-3987 Add support for various load balancing algorithms

- pom.xml
- scripts/hudson/narayana.sh
NO_TEST
(Includes some changes from https://github.com/jbosstm/narayana/pull/2381 - thank you @jmfinelli!. Also includes a bit of https://github.com/jbosstm/narayana/pull/2385/commits/4ddc62e8eda278e03f28f88771480f59be658b01)
> Adding GPG signing and change where to deploy snaphots to

- scripts/pre-release.sh
SCRIPT ONLY
Removed unused logic from pre-release.sh
> [SCRIPT] Removed unused logic from pre-release.sh

- client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java
- pom.xml
- test/basic/src/test/java/io/narayana/lra/arquillian/NarayanaLRAClientConfigIT.java
- test/basic/src/test/java/io/narayana/lra/arquillian/resource/TestClientResource.java
https://issues.redhat.com/browse/JBTM-3763
> JBTM-3763: Allow different configuration option of the LRA Coordinator URL in the NarayanaLRAClient

- .github/workflows/jacoco-profile.yml
- .github/workflows/lra-profile.yml
Improved current GH actions with labels
> [GITHUB_ACTIONS] Improved current GH actions with labels

- pom.xml
[JBTM-4002] Release profile fix
> [JBTM-4002] Release profile fix

- narayana-release-process.sh
- pom.xml
Removed the ability to release from `jbosstm`
> [JBTM-4002] further improvements

- pom.xml
Simplified nxrm3's configuration
> [JBTM-4002] Clean nxrm3

- .github/workflows/jacoco-profile.yml
- .github/workflows/lra-profile.yml
setting github actions testing by default. You can skip github actions testing using the "skip-tests" label
> GitHub actions testing by default

- .github/workflows/jacoco-profile.yml
- .github/workflows/lra-profile.yml
- .github/workflows/verify-format.yml
> [#80] GitHub Actions update

- arquillian-extension/pom.xml
- pom.xml
This is a test to replace #99 to see if it's as simple as removing the dependency on Weld SE.
> Dependabot/maven/org.wildfly.arquillian wildfly arquillian container managed 5.1.0.final

- arquillian-extension/src/main/java/io/narayana/lra/arquillian/ArquillianParametrized.java
needed for https://github.com/jbosstm/lra/issues/101
> Deprecation for junit5 next upgrade
